### ISSUE TITLE
Option to add cards as siblings

### ISSUE THREAD

**Issue by zolrak** [Glutanimate/image-occlusion-2-enhanced#12]
First of all, thank you for this wonderful add-on, it's very useful.

Is there a way to add the notes as siblings? I would like to study each individual note on different days, and I couldn't find a way to do this.

Also, is there a way to add more than one image at the same time?

Thanks you again!

**Comment by Glutanimate** [comment]
Hi,
thanks for your feature request. At this time there's no way of marking the cards as siblings. Because the number of occlusions produced is variable we would have to switch to a cloze deletion note type first (#2), but this comes with its own kind of problems. So for the time being I'd advise you to manually suspend all cards you don't plan on reviewing the same day and to then unsuspend them one by one as the days go by.

As for adding more images, there's no way to do this from within Image Occlusion, but you could edit your images in an image editor beforehand and then run IO on them.

**Comment by zolrak** [comment]
Thanks for the explanation! I'm going to do as you say.
