### ISSUE TITLE
Collection upload 

### ISSUE THREAD

**Issue by kabutar111** [Glutanimate/image-occlusion-2-enhanced#7]
After creating only 5 occlusion cards it's saying I have  to upload my collection and changes on another devices will be lost,  this is very big step back and I have  to go back to older version. 

Are you guys working on fix or this is the direction you guys are going in and this will always be there?? 

Although updated interface it's still as buggy as ever on Mac. (just to inform anyone who wish to update for sake of stability, it got sticky on trying to create first occlusion) 

Thank you for your efforts on this addon.

**Comment by kabutar111** [comment]
To add to above issue it leaves the image occlusion card type selected so to again create normal cloze normal cards you have to search cloze card type,  very troublesome if you have many card type,  never happened to me in original version.

**Comment by Glutanimate** [comment]
I take it this was the first time you used IO Enhanced? As stated in the README, IO Enhanced creates a new note type in order to provide features such as the remarks and sources fields. Any time a new note type is created Anki will perform a full collection sync. This is a one-time thing.

As far as the second point is concerned, this is also a result of running IO Enhanced for the first time. Anki automatically switches to a new note type whenever it's created.

**Comment by kabutar111** [comment]
Yes,  thank you got me scared for a minute,  I couldn't locate the above points in Readme file,  thank you for that. 

I would also like to confirm that this version is definitely twice stable as compared to original 2.0 build in contrast to my above assessment which seems to be first launch issue. 

Anothe related q does it upload multiple copies of image used for occlusion.?  I noticed that upload size for 300 kb image was over 1.5 mb,  which was more than what I noticed with original version.

**Comment by Glutanimate** [comment]
I figured most users would be familiar with how Anki manages note types, but I might update the README to make that aspect of the installation clearer.

It's unlikely that the add-on would cause duplication. IO Enhanced actually comes with changes meant to save space, e.g. when creating new image occlusion notes based on old ones. The increased upload size might have been because of unused media files. You can clear these via Tools → Check for unused media files (or something like that).

If you still experience increased upload sizes you can manually check your media collection to see if IO creates duplicate files. Under OS X it should be located somewhere under ~/Documents/Anki/User/collection.media. Not sure about the exact location as I don't use OS X.
